        name: Deploy

        on:
          push:
            branches:
              - main
        
        jobs:
          deploy:
            name: Deploy
            runs-on: ubuntu-latest
            steps:
              - uses: actions/checkout@v2
        
              - name: Sync
                uses: patrickwyler/gcs-bucket-sync-action@1.4
                with:
                  secrets: ${{ secrets.GCS_SA_KEY }}
                  bucket: 'gs://us-central1-composer-prod-19b6a35f-bucket/dags'
                  exclude: '.*\.md$|\.gitignore$|\.git/.*$|\.github/.*$'
        